apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: topknots-dev

resources:
- ../base

patchesStrategicMerge:
- deployment.yml

images:
- name: quay.io/pne_roberts/gatsby-simple-container
  newTag: 53bf56b75d618e05c7272bfe248aa3ce864fd043
namePrefix: test-
