apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: topknots-dev

resources:
- ../base
- ingress.yml

patchesStrategicMerge:
- deployment.yml

images:
- name: quay.io/pne_roberts/gatsby-simple-container
  newTag: e7550c4f56774ed4489008b142ea7e8933a67ed0
namePrefix: '{{github.head_ref}}'
