apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: topknots-dev

resources:
- ../base

patchesStrategicMerge:
- deployment.yml

images:
- name: quay.io/pne_roberts/gatsby-simple-container
  newTag: 3ff35138ba7d8d93dcd322cb0f36a3fd5fb0c456
namePrefix: test-
