apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: topknots-dev

resources:
- ../base

patchesStrategicMerge:
- deployment.yml

images:
- name: quay.io/pne_roberts/gatsby-simple-container
  newTag: c8acda7bc193e7b480ae25fd0e4ac5eb01cf493b
namePrefix: change-site
